version: "3"
services:
  sand:
    restart: always
    container_name: sand
    image: bookgin/sand
    build: ./
    depends_on:
      - redis
    ports:
      - "8080:8080/tcp"
    environment:
      UPLOAD_DIR: "/home/user/upload" # ./upload
      LISTEN_HOST: "0.0.0.0:8080" # 127.0.0.1:8080
      REDIS_HOST: "redis:6379" # 127.0.0.1:6379
      REDIS_PASSWORD: "" # ""
      REDIS_DB: "0" # 0
      GIN_MODE: "release" # debug
  redis:
    restart: always
    container_name: redis
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
