name: Unit Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2.4
        ports:
          - 6379:6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v
        env:
          REDIS_HOST: "redis:6379"
          UPLOAD_DIR: "/tmp"
